### ISSUE TITLE
When you move the card constantly and quickly, at the same time not move the card out, it will be crash.

### ISSUE THREAD

**Issue by ljk01200120** [Diolor/Swipecards#107]

**Comment by ljk01200120** [comment]
This is the crash log:

09-11 11:35:47.844: E/InputEventReceiver(2064): Exception dispatching input event.
09-11 11:35:47.854: E/MessageQueue-JNI(2064): Exception in MessageQueue callback: handleReceiveCallback
09-11 11:35:47.854: E/MessageQueue-JNI(2064): java.lang.NullPointerException
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.lorentzos.swipecards.MyActivity$1.onScroll(MyActivity.java:82)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.lorentzos.flingswipe.SwipeFlingAdapterView$1.onScroll(SwipeFlingAdapterView.java:245)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.lorentzos.flingswipe.FlingCardListener.resetCardViewOnStack(FlingCardListener.java:197)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.lorentzos.flingswipe.FlingCardListener.onTouch(FlingCardListener.java:118)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.View.dispatchTouchEvent(View.java:7709)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2238)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2476)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.View.dispatchPointerEvent(View.java:7894)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3995)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3874)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3561)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3618)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5580)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5560)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5531)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5660)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.os.MessageQueue.next(MessageQueue.java:138)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.os.Looper.loop(Looper.java:123)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at android.app.ActivityThread.main(ActivityThread.java:5049)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
09-11 11:35:47.854: E/MessageQueue-JNI(2064): 	at dalvik.system.NativeStart.main(Native Method)
09-11 11:35:47.864: E/AndroidRuntime(2064): FATAL EXCEPTION: main
09-11 11:35:47.864: E/AndroidRuntime(2064): Process: com.lorentzos.swipecards.example, PID: 2064
09-11 11:35:47.864: E/AndroidRuntime(2064): java.lang.NullPointerException
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.lorentzos.swipecards.MyActivity$1.onScroll(MyActivity.java:82)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.lorentzos.flingswipe.SwipeFlingAdapterView$1.onScroll(SwipeFlingAdapterView.java:245)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.lorentzos.flingswipe.FlingCardListener.resetCardViewOnStack(FlingCardListener.java:197)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.lorentzos.flingswipe.FlingCardListener.onTouch(FlingCardListener.java:118)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.View.dispatchTouchEvent(View.java:7709)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2238)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2476)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.View.dispatchPointerEvent(View.java:7894)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3995)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3874)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3561)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3618)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5580)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5560)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5531)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5660)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.os.MessageQueue.next(MessageQueue.java:138)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.os.Looper.loop(Looper.java:123)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at android.app.ActivityThread.main(ActivityThread.java:5049)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
09-11 11:35:47.864: E/AndroidRuntime(2064): 	at dalvik.system.NativeStart.main(Native Method)
09-11 11:35:48.724: E/QCALOG(312): [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
09-11 11:35:48.754: E/QCALOG(312): [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
09-11 11:35:48.764: E/QCALOG(312): [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]

**Comment by hieugie** [comment]
Change ur onScroll function like code below
 View view = flingContainer.getSelectedView();
                if (view !=null){
                    view.findViewById(R.id.item_swipe_right_indicator).setAlpha(scrollProgressPercent < 0 ? -scrollProgressPercent : 0);
                    view.findViewById(R.id.item_swipe_left_indicator).setAlpha(scrollProgressPercent > 0 ? scrollProgressPercent : 0);
                }
