### ISSUE TITLE
Card does not take fling listener

### ISSUE THREAD

**Issue by startxlabsdev** [Diolor/Swipecards#125]
When i set onClickListener to the child items, It does not take fling of cards. how can i overcome this issue?

**Comment by monpac** [comment]
I'm not understanding your problem. Could you explain it more clearly please? Thanks

**Comment by startxlabsdev** [comment]
my problem is something like this issue,
https://github.com/Diolor/Swipecards/issues/114

But if you can give a longClickListener and doubleTapListener on SwipeFlingAdapterView than also my problem will be solve.

**Comment by monpac** [comment]
Yes, you'll have to edit the FlingCardListener, as it is explained over there for any of that.

**Comment by AU3904** [comment]
When i set onClickListener to the child items (SimpleDraweeView),  i also find can not fling the cards, and i optimize it through this way: 

public class FlingSimpleDraweeView extends SimpleDraweeView {
    private boolean mIsScrolling;
    private int mTouchSlop;
    private float mDownX;
    private MainFragment.IFlingCardListener mFlingCardListener;

    public FlingSimpleDraweeView(Context context) {
        super(context);
    }

    public FlingSimpleDraweeView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public void setFlingCardListener(MainFragment.IFlingCardListener flingCardListener) {
        this.mFlingCardListener = flingCardListener;
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        final int action = MotionEventCompat.getActionMasked(event);
        switch (action) {
            case MotionEvent.ACTION_CANCEL:
                mIsScrolling = false;
                break;
            case MotionEvent.ACTION_DOWN:
                mDownX = event.getRawX();
                break;
            case MotionEvent.ACTION_MOVE:
                final int xDiff = calculateDistanceX(event);
                if (mFlingCardListener != null && xDiff != 0) {
                    if (xDiff > 50) {
                        mFlingCardListener.rightFling();
                    } else if (xDiff < -50) {
                        mFlingCardListener.leftFling();
                    }
                    mIsScrolling = true;
                    return true;
                } else {
                    break;
                }
            case MotionEvent.ACTION_UP:
                if (mIsScrolling) {
                    return true;
                } else {
                    break;
                }
        }

        return super.onTouchEvent(event);
    }

    private int calculateDistanceX(MotionEvent ev) {
        return (int) (ev.getRawX() - mDownX);
    }
}

i think this is  not best way ,but only a  tentative method.   if someone have a good idea  to fix it issue , pls share it . tks

**Comment by Diolor** [comment]
Close for the sake of #169
