### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tobiasschuerg** [Diolor/Swipecards#129]
Is this project dead?

**Comment by Diolor** [comment]
Unfortunately I had no time to focus on this project the previous months. I am writing now a v2.0 with the feedback I got so far here.

**Comment by tobiasschuerg** [comment]
ok. nice to hear. 
in case you mind, this app alsop uses your lib: https://play.google.com/store/apps/details?id=com.urbanchallenger.berlin

**Comment by Diolor** [comment]
Not at all. Happy to hear it's in use!
