### ISSUE TITLE
NullPointerException on using custom adapter

### ISSUE THREAD

**Issue by dvc009** [Diolor/Swipecards#13]
The code and the example work fine, but replacing the arrayadapter with a custom adapter is leading to a null pointer. What could be wrong?

**Comment by Sheikh-Aman** [comment]
Thanks everybody, it worked for me! :)

**Comment by hy9be** [comment]
Same with @nishant-git . Set the parent ViewGroup does not help. Still get null pointer exception, in Choreographer.doCallbacks()

**Comment by hy9be** [comment]
Figure out my issue. I call mFlingContainer.setFlingListener in a inner class of the Activity, thus result in a null pointer when SwipeFlingAdapterView calls onLayout at line 116: '''if(adapterCount < MAX_VISIBLE) mFlingListener.onAdapterAboutToEmpty(adapterCount);'''

**Comment by udayatom** [comment]
while loading the custom adapter,

Process: com.lorentzos.flingswipe, PID: 3399
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
	at com.lorentzos.flingswipe.SwipeFlingAdapterView.makeAndAddView(SwipeFlingAdapterView.java:142)
	at com.lorentzos.flingswipe.SwipeFlingAdapterView.layoutChildren(SwipeFlingAdapterView.java:124)
	at com.lorentzos.flingswipe.SwipeFlingAdapterView.onLayout(SwipeFlingAdapterView.java:109)
	at android.view.View.layout(View.java:15614)
	at android.view.ViewGroup.layout(ViewGroup.java:4968)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15614)
	at android.view.ViewGroup.layout(ViewGroup.java:4968)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
	at android.view.View.layout(View.java:15614)
	at android.view.ViewGroup.layout(ViewGroup.java:4968)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15614)
	at android.view.ViewGroup.layout(ViewGroup.java:4968)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1077)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5312)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by udayatom** [comment]
I need to make undo in swipe cards, i done as following but i am  not getting undo. please guide me.
	btnUndo.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View arg0) {
				// TODO Auto-generated method stub
		
				  addProducts.add(0, previousProductList.get(0));
				  System.out.println("Final list " + addProducts);
				  flingContainer.setAdapter(adapter); adapter = new
				  CustomAdapter(MainActivity.this, addProducts, null);
		  	adapter.notifyDataSetChanged();
			}
		});

	}

**Comment by rushank** [comment]
@udayatom  i want to also perform same thing. Have you find any solution for that?

**Comment by rushank** [comment]
@udayatom  i want to also perform same thing. Have you find any solution for that?

**Comment by udayatom** [comment]
Yes rushank, that issue was fixed... Thanks for replying :-)

**Comment by rushank** [comment]
can you guide me how can i perform that same thing? i am not able to perform that. :-(

**Comment by udayatom** [comment]
I think, problem here is adapter not updated properly, so we need explicitly update as follows.


Handler handler_notifyDatasetChanged = new Handler();
		handler_notifyDatasetChanged.postDelayed(new Runnable() {

			// Using handler with postDelayed called runnable run method

			@Override
			public void run() {
//implement  your undo mechanism here.

}

**Comment by rushank** [comment]
i want that undo mechanism . i have written your code  
  addProducts.add(0, previousProductList.get(0));
              System.out.println("Final list " + addProducts);
              flingContainer.setAdapter(adapter); adapter = new
              CustomAdapter(MainActivity.this, addProducts, null);
        adapter.notifyDataSetChanged();
but it is not working.

**Comment by rushank** [comment]
@udayatom how can i get undo item ?

**Comment by udayatom** [comment]
You create a one variable for storing the last position of the product, when u click undo, clear the existing products list and fill the items from the last position of the product list, don't forgot to adapter.notifyDataSetChanged();

**Comment by rushank** [comment]
But how can i get the position of that product.
   @Override
                    public void onLeftCardExit(Object dataObject) {
                      
                     // how to get position with this object?
                    }

how to get position from the Object ?

**Comment by udayatom** [comment]
you can use 
	@Override
public void removeFirstObjectInAdapter()
{
// here you store the value of removing card and you can able to get a position of the arraylist
}

**Comment by rushank** [comment]
i have  al.remove(0) in removeFirstObjectInAdapter() ; 
so how can it get the last position ???

**Comment by rushank** [comment]
@udayatom  please guide me how can i get last position.?

**Comment by udayatom** [comment]
@rushank, you need to declare a global variable count , because it knows like/dislike. just you increment that count variable inside   removeFirstObjectInAdapter(), This the relation of your removed card and position. This helps to get a last postion at undo. Enjoy :-)

**Comment by rushank** [comment]
can you give me guide me via code ? i have tried but i am able to undo the item. 
if possible then can you share some code of that?

**Comment by rushank** [comment]
My updated code:

 HomeScreenProduct tm;
    int hmpos = 0;
  
 flingContainer
                .setFlingListener(new SwipeFlingAdapterView.onFlingListener() {
                    @Override
                    public void removeFirstObjectInAdapter() {
                       
                        tm = getItem(hmpos);

                        remove(hmpos);

                      
                    }

                    @Override
                    public void onLeftCardExit(Object dataObject) {
                    
                        tm = (HomeScreenProduct) dataObject;

                        productid = tm.getProduct_id();

                    }

                    @Override
                    public void onRightCardExit(Object dataObject) {

                       
                    }


  private void remove(int index) {
        mArrayList.remove(index);
        mHomeviewAdapter.notifyDataSetChanged();
    }

    private void undo(int index, Object object) {
        // mArrayList = new ArrayList<HomeScreenProduct>();

        mArrayList.add(index, (HomeScreenProduct) object);


        mHomeviewAdapter = new HomeviewAdapter(
                getActivity(), mArrayList);
        flingContainer.setAdapter(mHomeviewAdapter);
        mHomeviewAdapter.notifyDataSetChanged();
    }

With this the the last item is undo in arraylist but when i try to bind the the card then it is not visible.
But when i have debug this -> In arraylist the last item is added to 0th position but not able to seen on fligncard.

**Comment by rushank** [comment]
@Diolor @tpaul1611 @dvc009 can you please help on this ?

**Comment by tpaul1611** [comment]
first thing i see is that you do not need to set the adapter again, notifyDataSetChanged should do the job. try not to change anything about the flingContainer, the adapter, or the list, only add or remove items from the list and notifyDataSetChanged, making a new list is bad and setting the adapter again wont do any good either. thats my two cents at the moment

**Comment by rushank** [comment]
i have also tried that. i  have also used below code:

      private void undo(int index, Object object) {
           mArrayList.add(index, (HomeScreenProduct) object);

             mHomeviewAdapter.notifyDataSetChanged();
       } 

but still it is not working.

**Comment by monpac** [comment]
When I implement the undo which adds the last object to a list & notifies the adapter, the view doesn't refresh and when i swipe the second card it appears back again. Any idea why?

```java

flingContainer.setFlingListener(new SwipeFlingAdapterView.onFlingListener() {
            @Override
            public void removeFirstObjectInAdapter() {
                Log.d("LIST", "removed object!");
                lastSwipe = al.get(0);
                al.remove(0);
                arrayAdapter.notifyDataSetChanged();
            }

            @Override
            public void onLeftCardExit(Object dataObject) {
                Log.i("APP", "EXIT LEFT");

                Snackbar.make(view, "", Snackbar.LENGTH_LONG)
                        .setAction("Undo", new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                Log.d("LAST SWIPE",lastSwipe.getName());
                                al.add(0,lastSwipe);
                                arrayAdapter.notifyDataSetChanged();
                            }
                        }).show();

            }

            @Override
            public void onRightCardExit(Object dataObject) {
                Log.i("APP", "EXIT Right");

                Snackbar.make(view, "Lindo Trabajo", Snackbar.LENGTH_LONG)
                        .setAction("Deshacer", new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                Log.d("LAST SWIPE",lastSwipe.getPropuesta());
                                al.add(0,lastSwipe);
                                arrayAdapter.notifyDataSetChanged();
                            }
                        }).show();
            }

            @Override
            public void onAdapterAboutToEmpty(int itemsInAdapter) {
                // Ask for more data here
                if(itemsInAdapter <= 4) {
                    al.add(quilmes);
                    arrayAdapter.notifyDataSetChanged();
                    Log.d("LIST", "notified");
                }
            }

            @Override
            public void onScroll(float scrollProgressPercent) {
                View view = flingContainer.getSelectedView();
                view.findViewById(R.id.item_swipe_right_indicator).setAlpha(scrollProgressPercent < 0 ? -scrollProgressPercent : 0);
                view.findViewById(R.id.item_swipe_left_indicator).setAlpha(scrollProgressPercent > 0 ? scrollProgressPercent : 0);
            }
        });

```

I tried getting lastSwipe onRightCardExit and I was unable to get the undo working, the same thing happened. Any help would be appreciated. Thanks.
