### ISSUE TITLE
Adding Swipe down

### ISSUE THREAD

**Issue by davidss20** [Diolor/Swipecards#130]
I would like to add some Swipe  down it will be tricky
Can you give me direction?

**Comment by wyb20151010** [comment]
i want it too,the total level like a pie.The bottom layer and the second bottom layer will show  it's foot. my poor english ,could anyone can understand me??

**Comment by vanshg** [comment]
This pull request adds the swipe up/down feature. https://github.com/Diolor/Swipecards/pull/65

**Comment by Diolor** [comment]
Close for the sake of #170
