### ISSUE TITLE
SwipeFlingAdapterView : Not reuse view

### ISSUE THREAD

**Issue by Sigvent** [Diolor/Swipecards#131]
The SwipeFlingAdapterView class doesn't reuse the created views.
Your concept is based on deleting the item in the adapter when the first card is flingged.

In SwipeFlingAdapterView .layoutChildren, you always ask the adapter to create a new view. So, if the user doesn't delete the flingged view in the adapter, there will be an out of memory.

**Comment by superlbr** [comment]
@Sigvent how to deal with?

**Comment by Sigvent** [comment]
@superlbr Good question, I don't know. I will try to change something to reuse the views. 
I'm so busy now. I will find a solution in a couple of months.

**Comment by Diolor** [comment]
it's adapter's responsibility to provide reusable views (cache). See "viewholder pattern"

**Comment by nihad92** [comment]
@Diolor yes this is adapter's responsibility, but SwipeFlingAdapterView does not support viewholder pattern. Please take a look at `View newUnderChild = mAdapter.getView(startingIndex, null, this);`
at `void layoutChildren(int startingIndex, int adapterCount)` method in Swipecards/library/src/main/java/com/lorentzos/flingswipe/SwipeFlingAdapterView.java class.
SwipeFlingAdapterView manually calling getView and always passing null for convertView param, So reusing implementation of viewholder pattern is not possible with SwipeFlingAdapterView. Even worst if you have 10 items in adapter and max_visible to 5 each time when you swipe left or right new 5 views are created. 

Could you please reopen issue, and include this in 2.0.0 will be nice?
