### ISSUE TITLE
How to set the initial position?

### ISSUE THREAD

**Issue by harolhiguera** [Diolor/Swipecards#133]

**Comment by Diolor** [comment]
Please provide more info about what the initial position is. Thanks!

**Comment by harolhiguera** [comment]
Hi Diolor, 

Sorry for my very late answer, well since I find myself doing some maintenance to an app I developed about a year ago, I still can't figure out how to set a specific position of the swipe at any point of time when the swipe is attached to an adapter with data. Thats is basically what I would like to resolve, i mentioned before that initial position because I thought about to clear the content and set the swipe in a specific position. Thanks man, I would really appreciate come advice, your library is awesome although in the library the method that would do that is disabled.  "setSelection(int)"
