### ISSUE TITLE
How can i get the index of the current card in right or left swipe?

### ISSUE THREAD

**Issue by tudorific** [Diolor/Swipecards#139]
Is it possible for me to get the index of the current card in onRightCardExit()?

I request a list of objects from a web service and the return value is saved to an ArrayList and that list is also used to populate the cards. Now when I swipe right, I want to know at which position was the car swiped so I can get the corresponding object from the ArrayList and modify a field. Can I do this?

**Comment by alexwalterbos** [comment]
The card that is swiped out is always at index 0 in the 'vanilla' form of the library. Is that what you mean?

**Comment by tudorific** [comment]
@alexwalterbos hmm, that could work if I remove the item at position 0 of my element arraylist as well. Thanks! I totally missed that the item was being removed *facepalm*

**Comment by alexwalterbos** [comment]
You're welcome ;) If that fixed the issue, please close this!
