### ISSUE TITLE
Custom Adapter instead of Array Adapter?

### ISSUE THREAD

**Issue by tudorific** [Diolor/Swipecards#140]
Hi,

I've created a custom adapter to use with my object rather than the simple ArrayAdapter since I need some extra fields, however, not all of my custom fields are showing up on the swipecard. 

With the following code the title, company name and description fields are correctly populated onto my card but not the others, even though the fields are there. No errors from the debugger and everything works fine but they just don't show up!!! What am I missing?

Here is what I am doing in my activity:

At the top of the activity:
`@InjectView(R.id.frame)` SwipeFlingAdapterView flingContainer;

In my AsyncTask:
```
arrayAdapter = new JobAdapter(getApplicationContext(), R.layout.jobcard, result);
flingContainer.setAdapter(arrayAdapter);
```

Yes: the result ArrayList is populated with values.

My adapter:
```

public View getView(int position, View convertView, ViewGroup parent) {
        View row = convertView;
        ViewHolder holder = null;

        LayoutInflater inflater = (LayoutInflater) context.getSystemService((Activity.LAYOUT_INFLATER_SERVICE));

        if (row == null) {
            row = inflater.inflate(layoutResourceId, parent, false);
            //row = inflater.inflate(layoutResourceId, null);

            holder = new ViewHolder();
            holder.title = (TextView)row.findViewById(R.id.tv_jobTitle);
            holder.payrate = (TextView)row.findViewById(R.id.tv_payRate);
            holder.startdate = (TextView)row.findViewById(R.id.tv_startDate);
            holder.workinghrs = (TextView)row.findViewById(R.id.tv_duration);
            holder.location = (TextView)row.findViewById(R.id.tv_location);
            holder.companyname = (TextView)row.findViewById(R.id.tv_companyName);
            holder.description = (TextView)row.findViewById(R.id.tv_JobDesc);
            holder.equipment = (TextView)row.findViewById(R.id.tv_equipmentReq);
            holder.experience = (TextView)row.findViewById(R.id.tv_experienceReq);

            row.setTag(holder);
        } else {
            holder = (ViewHolder)row.getTag();
        }

        Job j = jobs.get(0);

        holder.title.setText(j.getJobTitle());
        holder.payrate.setText(j.getPayrate());
        holder.startdate.setText(j.getDurationStart());
        holder.workinghrs.setText(j.getWorkingHrs());
        holder.location.setText(j.getLocation());
        holder.companyname.setText("ABC Company");
        holder.description.setText(j.getDescription());
        holder.equipment.setText("Hardhat");
        holder.experience.setText("3-5 years");

        return row;
    }
    static class ViewHolder
    {
        TextView title;
        TextView payrate;
        TextView startdate;
        TextView workinghrs;
        TextView location;
        TextView companyname;
        TextView description;
        TextView equipment;
        TextView experience;
    }
```

And finally, my jobcard.xml layout:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_gravity="center"
    android:layout_width="match_parent"
    android:layout_height="400dp"
    android:padding="20dp">

    <LinearLayout
        android:id="@+id/mainCardLayout"
        android:layout_width="match_parent"
        android:layout_height="340dp"
        android:layout_gravity="center"
        android:orientation="vertical"
        android:weightSum="1"
        android:background="#ffffff">

        <TextView
            android:id="@+id/tv_jobTitle"
            android:background="#ffffff"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="10dp"
            android:textStyle="bold"
            android:textSize="16sp"
            android:textColor="#474747"
            android:textAlignment="center"
            tools:text="Cement Pouring Guy"
            android:layout_gravity="center_horizontal"/>

        <TextView
            android:id="@+id/tv_companyName"
            android:background="#ffffff"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:textColor="#474747"
            android:textAlignment="center"
            tools:text="ABC Company"
            android:layout_gravity="center_horizontal" />

        <LinearLayout
            android:id="@+id/cardHeader"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_marginTop="20dp">

            <TextView
                android:id="@+id/tv_experienceReq"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="15dp"
                android:layout_marginLeft="10dp"
                tools:text="3-5 years" />

            <View
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="1" />

            <TextView
                android:id="@+id/tv_location"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="15dp"
                tools:text="Langley, BC" />

            <View
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="1" />

            <TextView
                android:id="@+id/tv_payRate"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="15dp"
                android:layout_marginRight="10dp"
                tools:text="125/day" />

        </LinearLayout>

        <TextView
            android:id="@+id/tv_JobDesc"
            android:textSize="14sp"
            android:textColor="#474747"
            android:background="#f3f3f3"
            tools:text="Pour Cement, Mix Cement, Level Cement and go pick up cement bags."
            android:layout_width="match_parent"
            android:layout_height="150dp"
            android:padding="15dp" />

        <LinearLayout
            android:id="@+id/additionalInfo"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center" >

            <TextView
                android:id="@+id/tv_startDate"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="15dp"
                android:layout_marginLeft="10dp"
                tools:text="June 1, 2016" />

            <View
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="1"
                />

            <TextView
                android:id="@+id/tv_duration"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="15dp"
                tools:text="8h" />

            <View
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="1"
                />

            <TextView
                android:id="@+id/tv_equipmentReq"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="15dp"
                android:layout_marginRight="10dp"
                tools:text="Hardhat" />

        </LinearLayout>

    </LinearLayout>

    <View
        android:id="@+id/item_swipe_left_indicator"
        android:alpha="0"
        android:layout_width="20dp"
        android:layout_height="20dp"
        android:layout_margin="20dp"
        android:background="#A5F" />

    <View
        android:id="@+id/item_swipe_right_indicator"
        android:alpha="0"
        android:layout_width="20dp"
        android:layout_height="20dp"
        android:layout_margin="20dp"
        android:layout_gravity="right"
        android:background="#5AF" />

</FrameLayout>
```

Thanks for the help!

**Comment by tudorific** [comment]
@alexwalterbos any chance you can help me out with this one?

**Comment by alexwalterbos** [comment]
I think this has to do with the holder losing the reference to the `TextView`s, but that's a pretty wild guess. Try to see if the holder you get at `holder = (ViewHolder)row.getTag();` is populated.

Could you post the code for your adapter and viewholder if that doesn't work?

Unrelated, but while I'm at it:

> LayoutInflater inflater = (LayoutInflater) context.getSystemService((Activity.LAYOUT_INFLATER_SERVICE));

Protip: `LayoutInflater.from(Context context)`, [read more here](http://developer.android.com/reference/android/view/LayoutInflater.html#from(android.content.Context))

> Job j = jobs.get(0);

You don't use `position` but always get the first job in the list. This shouldn't cause the problem at hand, but just a heads-up.

**Comment by tudorific** [comment]
@alexwalterbos Thanks for the tips. 

As for the `holder = (ViewHolder)row.getTag()` execution doesn't actually go into the else, it always has a null view so it assigns values to the TextViews. Stepping through that part of the code, all the TextViews are assigned values but they just don't display back on the SwipeCard. Interestingly enough, some of the values do display, such as JobTitle, CompanyName, and Description....I'm really confused :( 

Here is my entire code for the adapter:

`
public class JobAdapter extends ArrayAdapter<Job> {
    private final Context context;
    private final ArrayList<Job> jobs;
    private final int layoutResourceId;

    public JobAdapter(Context context, int layoutResourceId, ArrayList<Job> jobs) {
        super(context, layoutResourceId, jobs);
        this.context = context;
        this.jobs = jobs;
        this.layoutResourceId = layoutResourceId;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View view = convertView;
        ViewHolder holder = null;

        LayoutInflater inflater = (LayoutInflater) context.getSystemService((Activity.LAYOUT_INFLATER_SERVICE));

        if (view == null) {
            view = inflater.inflate(layoutResourceId, parent, false);

            holder = new ViewHolder();
            holder.title = (TextView)view.findViewById(R.id.tv_jobTitle);
            holder.payrate = (TextView)view.findViewById(R.id.tv_payRate);
            holder.startdate = (TextView)view.findViewById(R.id.tv_startDate);
            holder.workinghrs = (TextView)view.findViewById(R.id.tv_duration);
            holder.location = (TextView)view.findViewById(R.id.tv_location);
            holder.companyname = (TextView)view.findViewById(R.id.tv_companyName);
            holder.description = (TextView)view.findViewById(R.id.tv_JobDesc);
            holder.experience = (TextView)view.findViewById(R.id.tv_experienceReq);

            view.setTag(holder);
        } else {
            holder = (ViewHolder)view.getTag();
        }

        Job j = jobs.get(0);

        holder.title.setText(j.getJobTitle());
        holder.payrate.setText(j.getPayrate());
        holder.startdate.setText(j.getDurationStart());
        holder.workinghrs.setText(j.getWorkingHrs());
        holder.location.setText(j.getLocation());
        holder.companyname.setText("ABC Company");
        holder.description.setText(j.getDescription());
        holder.experience.setText("3-5 years");

        //TODO: add hardhat, boots and other field to objects mapped

        return view;
    }
    static class ViewHolder
    {
        TextView title;
        TextView payrate;
        TextView startdate;
        TextView workinghrs;
        TextView location;
        TextView companyname;
        TextView description;
        TextView experience;
    }
}
`
Note that I change the row variable to view since row didn't make sense as I am not using a ListView. 

Thanks for the help!

**Comment by tudorific** [comment]
@alexwalterbos well I figured it out and I feel like an idiot haha. Turns out I didn't define a text color in my xml file so the fields were being populated but with white text so I couldn't see the values. After changing the color, the adapter works fine :). Thanks for the help!

**Comment by alexwalterbos** [comment]
Haha it happens to the best. No problem!
