### ISSUE TITLE
Getting  Parameter from a Card

### ISSUE THREAD

**Issue by davidm06** [Diolor/Swipecards#142]
Hi

Nice project, hope I will be ble to use it
Here my issue.

MY NEED : getting a paramter that identify the card in my database (let say "IdCard=12345" for example)

What I did : 
I modifyed the Data class by adding IdCard parameter (so a card will have an image, a text AND an ID get from my database)

I created the card according my new class such as : 

    al.add(new Data("http://i.ytimg.com/vi/PnxsTxV8y3g/maxresdefault.jpg", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",12345));

PROBLEM : I do not know how to get back this parameter, when a card is swaped ,I need to use it to perform a remote update on my website

Many thanks for your help
David

**Comment by ashutosh2k12** [comment]
Implement `removeFirstObjectInAdapter()` in your `flingListener()` and remove the topmost element of array. i.e. you should implement `al.remove(0)`, just as mentioned in README. Then you should have the top element of array as the swiped card. Thus, the code will look something like:

```
flingContainer.setFlingListener(new SwipeFlingAdapterView.onFlingListener() {

            @Override
            public void removeFirstObjectInAdapter() {
                al.remove(0);
                arrayAdapter.notifyDataSetChanged();
            }

            @Override
            public void onLeftCardExit(Object dataObject) {
                Data carddata = al.get(0); //Now access the data property and get you card details
              // String cardID = carddata.getCardId(); //Assuming this method returns cardId
            }
            
            @Override
            public void onRightCardExit(Object dataObject) {
                Data carddata = al.get(0); //Now access the data property and get you card details
              // String cardID = carddata.getCardId(); //Assuming this method returns cardId
            }
});

**Comment by davidm06** [comment]
many thanks !
