### ISSUE TITLE
Not able to set Dynamic Data

### ISSUE THREAD

**Issue by tchawla2** [Diolor/Swipecards#143]
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference

I am getting this error. I don't know what is wrong. As soon as the adapter is called, the application kills. Somebody please help me. It's kinda urgent.

**Comment by alexwalterbos** [comment]
You're probably calling methods on parts of your view before they are inflated. Post the code where this is thrown (and related code) if you need more help.
