### ISSUE TITLE
How to add like of current card on right and dislike on left?

### ISSUE THREAD

**Issue by WaqarAhmadAwan** [Diolor/Swipecards#148]
Hello!
I am developing an app using swipe card library and I want to store like and dislikes in data base so tell me a method how to add cards as a like on right and dislike on left?

**Comment by WaqarAhmadAwan** [comment]
When I swipe right I want to add that card as like how to do that kindly help me.
Thanks

**Comment by Diolor** [comment]
This is personal implementation and not part of this library.
