### ISSUE TITLE
White flash / flickers displaying new cards

### ISSUE THREAD

**Issue by JeffIden** [Diolor/Swipecards#150]
Hi,

I use this component for a job-dating app and just after a card has been swiped and the new card is displayed, I have a white flash on the new card when it refreshes (with getView function).

Maybe it's not the component but the use of NetworkImageView with Volley.
Has anyone encountered this behavior before ?

Thanks,
Jeff

**Comment by alexwalterbos** [comment]
You could check if the view has not been inflated in the `getView` call. Do you tamper with the `View` visibility? Haven't encountered such behavior.

**Comment by JeffIden** [comment]
Yes, I do inflate the view in the getView call : 
ViewHolder vh = null;
            LayoutInflater mInflater = (LayoutInflater) mContext
                    .getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
            if (convertView == null) {
                convertView = mInflater.inflate(R.layout.item, parent, false);
                vh = new ViewHolder();
                vh.mOpportunityPic = (NetworkImageView) convertView.findViewById(R.id.cardPic);

                vh.mSmallIcon = (ImageView) convertView.findViewById(R.id.smallIcon);

                vh.sTitle = "";
                convertView.setTag(vh);
            }

            vh = (ViewHolder) convertView.getTag();

I didn't touch the View visibility.

**Comment by JeffIden** [comment]
I just replaced my Volley call by 
 Glide.with(context)
    .load("http://inthecheesefactory.com/uploads/source/glidepicasso/cover.jpg")
    .into(ivImg);

and it works !

I close the ticket :)
