### ISSUE TITLE
Custom Adapter with OnClickListener no longer swipeable?

### ISSUE THREAD

**Issue by tudorific** [Diolor/Swipecards#154]
I created a Custom Adapter for the swipe cards and it has multiple fields. In the adapter, I have a onClickListener which opens a fragment. Essentially, I have a description textview that is 5 lines on the card, when the user taps the textview I want to open a fragment and display all of the description lines. 

What I have noticed, is that since I made the description field clickable, as in I added the onClickListener, I can no longer swipe the card by dragging from that description field. If i swipe by dragging from any other area on the card it works fine...what could cause this? Can I not have a clickable field on a swipe card?

Here is my onClickListener method:

```
holder.description.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // Open up a fragment to display the entire description
                    Toast.makeText(context, "Open Description", Toast.LENGTH_SHORT).show();

                    DescFragment frag = new DescFragment();
                    frag.setArguments(fragmentParams);

                    ((MainActivity) context).getSupportFragmentManager().beginTransaction()
                            .add(R.id.fragment_container, frag).commit();
            }
        });
```

Thanks in advance for the help!

**Comment by TormundsMember** [comment]
@tudorific Since this was closed, what was your solution to make it clickable?
