### ISSUE TITLE
Implementing undo functionality

### ISSUE THREAD

**Issue by arpitgoyal2008** [Diolor/Swipecards#160]
Hi,

Is there a way I can bring old cards back after it has been swiped left? Also, is there an animation to bring card back?

If I don't add

```
                     public void removeFirstObjectInAdapter() {
                                    articles.remove(0);
                                    adapter.notifyDataSetChanged();
                                    Log.d("LIST", "removed object!");
                                }
```

then the next card just freezes.
Thanks,
Arpit

**Comment by Diolor** [comment]
These are 2 different topics. For the second you need this code to remove the item from the adapter. The adapter will take and animate always the top (first) view.

**Comment by Diolor** [comment]
Regarding undo I opened #168
