### ISSUE TITLE
How to Rewind the card which was already swiped

### ISSUE THREAD

**Issue by kiranlanke** [Diolor/Swipecards#174]
Hi, Thank you for sharing this Swipe cards in github. I'm trying to rewind the card which was already swiped (left or right side swipe) with animation. For this requirement i tired lots but i failed to achieve this. Can you give any idea to how to rewind or resume the card with animation?

Thank you.......

**Comment by Diolor** [comment]
Hi you need to implement a reverse animation from the edge. Then add the item in the 0 position of your adapter's list.
