### ISSUE TITLE
Dragging of card is slow

### ISSUE THREAD

**Issue by IOException722** [Diolor/Swipecards#186]
Dragging top card on screen is very slow.
How to make dragging top card smooth??

**Comment by rushabh1191** [comment]
@IOException722 It happened to me too. I was showing images in every card,so view became heavy. I scaled down image so it is working fine now. Just check if there is any heavy view on the card. And try to optimize it. It might work for you. :)

**Comment by IOException722** [comment]
Thank you for the suggestion. I used different library and customized according to my app requirements. Working well .
