### ISSUE TITLE
Disable swipe & only listen for click

### ISSUE THREAD

**Issue by CptSparkz** [Diolor/Swipecards#192]
I want to achieve that the first card is only clickable and not movable. On click, I want to change to the next card and add the fling functionality. I want to iterate through all cards like this.

What I managed to do was is using [this](https://github.com/Diolor/Swipecards/pull/92) to disable the actual out-of-screen swipe of the cards, but I can't find a way to make the card not move at all.

- How can I achieve this?
- Is there any way to disable a cards movement while listening for onItemClick?

**Comment by maduperera** [comment]
Yeah I too would love to know about this.I need only the buttons to do the animation without moving from finger.

**Comment by CptSparkz** [comment]
Well, I managed to do that by adding onClickListener to the LinearLayout inside the CardView. The Code for onClickListener is inside a custom Adapter.
This way you are unable to swipe the card unless you change the visibility of the LinearLayout to GONE or INVISIBLE.

**Comment by maduperera** [comment]
Hi @CptSparkz,
Thanks buddy. It helped. Sorry for the late reply.

Regards,
Madusha
