### ISSUE TITLE
Cards not displaying properly

### ISSUE THREAD

**Issue by ynnadkrap** [Diolor/Swipecards#20]
I tried creating a dummy example with 6 cards which only contain text. This is what they look like: 
![screen shot 2014-11-12 at 8 56 56 pm](https://cloud.githubusercontent.com/assets/2474082/5022162/850727d4-6aae-11e4-86ba-ac6ba33a2438.png)

xml:

```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MyApp">

    <com.lorentzos.flingswipe.SwipeFlingAdapterView
        android:id="@+id/explore_cards"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#eee9e2"
        />

</RelativeLayout>
```

build.grade:

```
compile 'com.android.support:support-v4:18.0.+'
compile 'com.android.support:appcompat-v7:18.0.+'
compile 'com.lorentzos.swipecards:library:1.0.7@aar'
```

relevant pieces of java:

```
SwipeFlingAdapterView swipeView = (SwipeFlingAdapterView) v.findViewById(R.id.explore_cards);
tempArray = new ArrayList<String>();
tempArray.add("hi");
tempArray.add("hey");
tempArray.add("yo");
tempArray.add("blah");
tempArray.add("hin");
tempArray.add("heeeee");
swipeView.setAdapter(arrayAdapter);
swipeView.setFlingListener(this);

...........

@Override
public void removeFirstObjectInAdapter() {
    Log.i(LOG_TAG, "REMOVE FIRST");
    tempArray.remove(0);
    arrayAdapter.notifyDataSetChanged();;
}

@Override
public void onLeftCardExit(Object o) {
    Log.i(LOG_TAG, "EXIT LEFT");
}

@Override
public void onRightCardExit(Object o) {
    Log.i(LOG_TAG, "EXIT RIGHT");
}

@Override
public void onAdapterAboutToEmpty(int i) {
    Log.i(LOG_TAG, "ABOUT TO EMPTY");
}
```

I suppose it's also worth mentioning that this is all placed inside a (support) Fragment. I also get a message in my XML file stating 'Failed to find style 'SwipeFlingStyle' in current theme'

Any help would be appreciated, thanks a bunch!

**Comment by alexgomes09** [comment]
I am getting this same  issue now. Card doesnt show. Showing layout rendering problem but I copied all styles/attributes that I found inside example and library folder. No console error either.  :cry: 

![screen shot 2015-10-07 at 12 44 05 pm](https://cloud.githubusercontent.com/assets/6835177/10344417/22c0af8c-6cf1-11e5-8f2a-47c1955c53ce.png)

**Comment by alexgomes09** [comment]
After so much trial finally figured out that it doesn't show inside ScrollView which was my parent view. Changed it to RelativeView and all worked. But I really need that ScrollView

**Comment by viveka12** [comment]
@ynnadkrap What was the solution? I have the same problem!

**Comment by alexgomes09** [comment]
@viveka12  - Hey, this might be helpful to take a look. For me it was the issue with scrollview. For some reason this library doesn't work with scrollview. Maybe because scrollview has scroll event on them and library gets confused whether to scroll the screen or swipe cards.  Try changing parent layout to Relative / Linear or Frame layout.

**Comment by arnaud-zg** [comment]
It just tries to find a style name `SwipeFlingStyle` in your theme, that's worked for me.
```
    <style name="AppTheme.Cyan" parent="Theme.AppCompat.NoActionBar">
        ...
        <item name="SwipeFlingStyle">@null</item>
    </style>
```
