### ISSUE TITLE
Swiping in ViewPager

### ISSUE THREAD

**Issue by ynnadkrap** [Diolor/Swipecards#21]
I tried including this view within a ViewPager, but the swiping mechanism is buggy. It'll only swipe right if the page is the first in the PagerAdapter and left if the page is the last in the PagerAdapter. Is there any workaround for this, or are you planning on implementing this feature anytime in the near future?

**Comment by ibrelm** [comment]
> There's an easy fix for this. If anyone wants to implement SwipeFlingAdapterView within a ViewPager, you just need to create a custom class that extends ViewPager and override the canScroll(...) method.
> 
> Example:
> 
> ```
> public class CustomViewPager extends ViewPager {
> .......
>     @Override
>     protected boolean canScroll(View v, boolean checkV, int dx, int x, int y) {
>         if (v instanceof SwipeFlingAdapterView) return true;
>         return super.canScroll(v, checkV, dx, x, y);
>     }
> ........
> }
> ```

thanks it is working
