### ISSUE TITLE
how to create stack. 

### ISSUE THREAD

**Issue by harminderclabs** [Diolor/Swipecards#27]
I want to create a stack of 3 cards to be shown at once i.e little layer of below card to be shown.
So user get to know that there is more cards below. 

Your library do have methods of class SwipeFlingAdapterView but these doesn't work or this indicate something different that  I am not able to understand.
1. setMinStackInAdapter(3);
2. setMaxVisible(3);

Please help if there is any method regarding this.

Thanks in Advance.

**Comment by jainrocks** [comment]
@Diolor  Can you please explain it, I am unable to understand how these cards are placed in the layout and method onAdapterAboutToEmpty() is called only when I am on card "CSS" according to example, it doesn't matter whether app:min_adapter_stack="6" or 5 or 1 used.

**Comment by kh0r** [comment]
Quick and dirty:
```
        arrayAdapter = new ArrayAdapter<String>(this, R.layout.item, R.id.helloText, al ) {
            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                View v = super.getView(position, convertView, parent);
                // make a nice stack of cards
                v.setTranslationY(position*10);
                return v;
            }
        };
```

**Comment by hy9be** [comment]
@kh0r I set a drawable as the border of the card. Using ``setTranslationX``, ``setTranslationY``, the border drawable is still presented after I swiped and removed the card. Any idea?

**Comment by hy9be** [comment]
@kh0r I had it resolved by calling the ``invalidate()`` method of ``SwipeFlingAdapterView`` in ``removeFirstObjectInAdapter`` callback. But do have performance concern.
