### ISSUE TITLE
How do I use this with images?

### ISSUE THREAD

**Issue by hackathoner** [Diolor/Swipecards#34]

**Comment by myfknoll** [comment]
One approach is to create your own ArrayAdapter with your custom CardModel and layout.
In your adapter there you load an image into the ImageView.

**Comment by jainrocks** [comment]
Can you please elaborate more as I am very much interested in perfoming this task

**Comment by fadelakin** [comment]
How does one do this?

**Comment by Diolor** [comment]
Please see what @myfknoll explained
