### ISSUE TITLE
Incorrect Draw

### ISSUE THREAD

**Issue by gangD** [Diolor/Swipecards#35]
Hi, Diolor,

```
 First, thanks for your project. I find one problem, but I can't find the solution, could you give some help. The problem is as shown in follow image.
```

![device-2015-01-14-165937](https://cloud.githubusercontent.com/assets/5096252/5736412/787f839c-9c10-11e4-88b1-6d4530475141.png)

**Comment by Diolor** [comment]
This should be from the library
