### ISSUE TITLE
More user guides

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [Diolor/Swipecards#37]
Hi all, not so much a bug but as a new developer I find it hard to extend this much beyond the example. It would be great to see some example code/a bit more explanation on perhaps how images could be added and what not. 

I am going to try and work through it and create some sort of sample project, but I am not sure I'll be able to. Any help with this I believe would be appreciated by the wider android community.

edit: These are the main questions I had whilst trying to get the example working. I will work on it over the weekend and see if I can answer any myself but if anyone can provide answers I'd appreciate it. Perhaps then we could then put them into a guide for future reference.

Could you have different item.xml per card? How would this be achieved? (I have a feeling this would be done with array adapter, but I am not familiar with them and am not sure how to do it).

(Linked to above) Could each card contain a different layout? what layout is suitable to put onto a card? how would you achieve this?

Could you have a stack of google now style cards (perhaps https://github.com/afollestad/Cards-UI)?

I think if someone can help me answer the first question, I can answer the ones that follow.

-Matt

**Comment by alexwalterbos** [comment]
If you provide more specific questions, I'm sure we'll be able to answer them. You could also write down your findings and progress, and offer those as a tutorial.

**Comment by MatthewJamesBoyle** [comment]
Hi Alex, added some specific questions.

Many thanks,
Matt

**Comment by alexwalterbos** [comment]
You provide your `SwipeFlingAdapterView` with an adapter using `setAdapter()`. This `BaseAdapter
