### ISSUE TITLE
Spammy Errors

### ISSUE THREAD

**Issue by JamesCullum** [Diolor/Swipecards#40]
About every second i actively use the Library in the App, i get about 1-5 error messages with the following pattern: 

`01-30 00:26:03.126    3211-3211/name.of.my.app E/ClipboardServiceEx﹕ clipEx is android.sec.clipboard.ClipboardExManager@1874208`
`01-30 00:26:03.126    3211-3211/name.of.my.app E/ClipboardServiceEx﹕ clipEx has text data : false`

I use Android 5.0 on Samsung S5. As i use the dependencie i can't fix it myself.

**Comment by Diolor** [comment]
Probably something internal from Samsung. Feel free to reopen if you have more info
