### ISSUE TITLE
Customizable Layouts

### ISSUE THREAD

**Issue by JamesCullum** [Diolor/Swipecards#41]
At the moment you can only give one layout and a block of text to the library.
It'd be good to have at least two of them - one background image (drawable) and the text.
Or just get any more open API to let us customize it ourself, like just giving a handler that also customizes the design.

**Comment by Diolor** [comment]
@JamesCullum You can happily add whichever layouts you want and as many types you like in your adapter.

Several tuts and SO questions:
https://www.google.de/search?client=safari&rls=en&q=adapter+two+types+android&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=iILLVJzEO-KH8Qfl2oAI
