### ISSUE TITLE
Adapter does not visible

### ISSUE THREAD

**Issue by eGorets** [Diolor/Swipecards#5]
Hi, I try to implement your gradle libs to me project, but i have a little issue, SwipeFlingAdapterView does not visible in me view. I created custom BaseAdapter and set up it

swipeFlingAdapterView.setAdapter(adapter);

but nothing to show in layout except button

**Comment by SyedWasiHaider** [comment]
This is still an issue. I just created a very simple custom adapter and it was just blank when I ran it.

**Comment by Sandeep1620** [comment]
Hello Dilor.

In first place thank you for you effort .

My question is when I want to swipe Images instead of text with custom BaseAdapter .Nothing is working for me ,it is giving null pointer exception,please help to let me whether I can set Custom Adapter or not .
