### ISSUE TITLE
Image on card underneath is not displayed when card above is partially swiped.

### ISSUE THREAD

**Issue by uditmukherjee** [Diolor/Swipecards#51]
Hi Diolor, first of, awesome library.

I am using this library with images and some text. The issue is when a card is partially swiped, the image in the card underneath is not drawn. The image gets drawn only after the card above is fully swiped. This is not the case for the text underneath, the text is shown when the card is partially swiped. I want this behavior to apply for the image also.

I'm trying to achieve something where you can sneak peek fully what's below the card.

Please let me know if there's a solution to this.

Cheers

**Comment by infinity8942** [comment]
I have the same issues.

**Comment by jayantibutani** [comment]
i have also this problem while getting image from server side

**Comment by jdoes** [comment]
+1

**Comment by jayantibutani** [comment]
first you download all image getting from server and then after set bitmap from adapter using imageloader

**Comment by uditmukherjee** [comment]
Using Picasso instead of Universal Image loader solved it for me.

**Comment by jayantibutani** [comment]
you can directy load image url from server and display one by one

**Comment by sametheridge** [comment]
+1 for Picasso, solved the problem for me too
