### ISSUE TITLE
How to set the FrameLayout height used in the item.xml by getView function ?

### ISSUE THREAD

**Issue by jainrocks** [Diolor/Swipecards#52]
I have used custom Adapter and item.xml contains Imageview along with TextView. I want to change the height and width of the FrameLayout and of the contained ImageView dynamically.
I have written below code, but no cards visible when I run this piece of code. Library is awesome, I don't want to change the library, So please help me. 
<code>

       public View getView(final int position, View convertView, ViewGroup parent) {
           View view = inflater.inflate(R.layout.item, parent, false);
            final Holder holder = new Holder();
            holder.ivPhoto = (ImageView) view.findViewById(R.id.ivImage);
            holder.ivInfo = (TextView) view.findViewById(R.id.ivInfo);        
            holder.frame_layout = (FrameLayout) view.findViewById(R.id.frame_layout);        

            holder.frame_layout.setLayoutParams(new FrameLayout.LayoutParams(width/2, height/2));        
            return view;
       }

    private class Holder {
        private ImageView ivPhoto;
        private TextView ivInfo;        
        private FrameLayout frame_layout;        
    }
</code>

I am getting height "height and width" as follows:
<code>
	DisplayMetrics displaymetrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(displaymetrics);
        int width = displaymetrics.widthPixels;
	int height = displaymetrics.heightPixels;
</code>

If I am doing something wrong please correct me.

**Comment by zaur** [comment]
I do it like this:
    private void fixSize(final View view) {
        LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) view.getLayoutParams();
        params.height = photoDimension;
        params.width = photoDimension;
        view.setLayoutParams(params);
    }

first I get the params assigned to a view by when inflating from xml, then I set width and height programmatically.
