### ISSUE TITLE
Speed up / optimise card swiping

### ISSUE THREAD

**Issue by qbait** [Diolor/Swipecards#63]
On low-end devices cards swiping is pretty laggy. There is some easy way to speed up cards swiping?

**Comment by jonasborggren** [comment]
I noticed by removing the rotation it was radically improved.

**Comment by hy9be** [comment]
@jonasborggren Do you mean by removing the ``app:rotation_degrees="15.5"`` in layout.xml?

**Comment by Nidre** [comment]
@qbait  @jonasborggren  @hy9be 

I have implemented recycling as suggested https://github.com/Diolor/Swipecards/issues/72 and also removed rotation animation. In my app it is quite stable and fast.

You can check the repo here: https://github.com/Nidre/Swipecards
I've also added, drag threshold and ability animate the card behind the first card synchronized with the first cards animation.

**Comment by X4mp** [comment]
@Nidre is there a chance to get your code into this repository? I would really need this update.
Also it would be great if @Diolor could merge @Nidre 's pull-request then and release a new version.

**Comment by X4mp** [comment]
@Nidre could you push a version which contains the recycling but not the removed rotation animation to your repository?

**Comment by Nidre** [comment]
@X4mp Sorry I wouldn't able to that. But It is fairly easy to implement recycling mentioned in https://github.com/Diolor/Swipecards/issues/72 .

**Comment by hy9be** [comment]
@qbait @X4mp just apply ``setLayerType(View.LAYER_TYPE_HARDWARE, null)`` to your visible convertViews in adapter.
