### ISSUE TITLE
Swiping a card programmically

### ISSUE THREAD

**Issue by TT1943** [Diolor/Swipecards#69]
Hi, I want to swipe a card programmatically when user clicks on "like" button instead of manually swipe it. How can I achieve this? Also I tried:
mAdpater.remove(0);
mAdapter.notifyDataSetChanged();
This code won't force the first card being removed. Is there a way to do so?

**Comment by alexwalterbos** [comment]
Use `SwipeFlingAdapterView.getTopCardListener()` on your instance of `SwipeFlingAdapterView`. On the listener you can call `selectLeft()` or `selectRight()`.

**Comment by TT1943** [comment]
Thanks, it just works. I am going to close this ticket. :+1:
