### ISSUE TITLE
Toggle button State is not detecting 

### ISSUE THREAD

**Issue by anantshah93** [Diolor/Swipecards#74]
Inside SwipeFlingAdapterView when I used Toggle button it is not detecting its state and shows null pointer reference.ASAP give Solution/Answer
(Even i texted code in separate layout, and in Same Layout(by using tow controls toggle and swipeFlingAdapterView)).

Thank You,
Anant Shah

**Comment by alexwalterbos** [comment]
Could you post your code?

**Comment by anantshah93** [comment]
I Found Solution of my problem, I have to register toggle button inside the adapter and set its property focusable="false" and then create interface and listener to handle its events.
