### ISSUE TITLE
Use custom font?

### ISSUE THREAD

**Issue by DannyTsegai** [Diolor/Swipecards#81]
How can we replace the font in the Swipecards with a custom font(.ttf)?

**Comment by Diolor** [comment]
This is a general Android question and not library related

**Comment by DannyTsegai** [comment]
It is library related, actually. The way this library works is that we call setContentView() on activity_m.xml which simply hosts a SwipeFlingAdapterView. That means that the only view we can retrieve via findViewById() is the SwipeFlingAdapterView and NOT the TextView from item.xml which is the object we need to get a hold of in order to change the TextView's font to our custom font. 

This means that the usual way of setting a custom font to a TextView:

Typeface myTypeface = Typeface.createFromAsset(getAssets(), "fonts/myFont.ttf");
TextView myTextView = (TextView)findViewById(R.id.myTextView);
myTextView.setTypeface(myTypeface);

Doesn't work and we get a NullPointerException on the "myTextView.setTypeface(myTypeface);" statement.

**Comment by xsorifc28** [comment]
You can customize the font and other attributes inside your adapter's viewholder class.

**Comment by DannyTsegai** [comment]
@xsorifc28 How exactly would that be done in code?

**Comment by xsorifc28** [comment]
What kind of adapter are you using?  Can you post your code?

**Comment by DannyTsegai** [comment]
ArrayAdapter.

**Comment by xsorifc28** [comment]
Something like:

    ArrayAdapter arrayAdapter = new ArrayAdapter<String>(this, R.layout.item, items) {
    @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                View v = super.getView(position, convertView, parent);
                TextView tv = v.findViewById(R.id.mytextview)
                 /* modify any of the views as you'd like */
                return v;
            }
        };

or you can create a new adapter whic extends ArrayAdapter.

**Comment by nishantmendiratta** [comment]
Thanks @xsorifc28 this one worked like a charm. 👍
