### ISSUE TITLE
How to show swipe_indicators?

### ISSUE THREAD

**Issue by vleango** [Diolor/Swipecards#82]
I would like to show the swipe_left_indicator / swipe_right_indicator, but haven't figured out how to do so yet. I know I should do it `onScroll`, but how do I get the view?

I tried this onCreate:
```
mLeftSwipe = findViewById(R.id.item_swipe_left_indicator);
mRightSwipe = findViewById(R.id.item_swipe_right_indicator);
```

Can someone lend a hand? Thanks.

**Comment by vleango** [comment]
This is what I ended up doing:
```
@Override
            public void onScroll(float position) {

                View view = flingContainer.getSelectedView();
                mLeftSwipe = view.findViewById(R.id.item_swipe_left_indicator);
                mRightSwipe = view.findViewById(R.id.item_swipe_right_indicator);

                if(position == 0) {
                    mLeftSwipe.setAlpha(0);
                    mRightSwipe.setAlpha(0);
                }
                else if(position > 0) {
                    mLeftSwipe.setAlpha(position);
                }
                else {
                    mRightSwipe.setAlpha(Math.abs(position));
                }

            }
```

Is there a better way?

**Comment by xsorifc28** [comment]
This is from the sample app: 

           @Override
            public void onScroll(float scrollProgressPercent) {
                View view = flingContainer.getSelectedView();
                if (view != null) {
                    view.findViewById(R.id.item_swipe_right_indicator).setAlpha(scrollProgressPercent < 0 ? -scrollProgressPercent : 0);
                    view.findViewById(R.id.item_swipe_left_indicator).setAlpha(scrollProgressPercent > 0 ? scrollProgressPercent : 0);
                }

            }
