### ISSUE TITLE
What's the fastest way to create card animation for undo feature?

### ISSUE THREAD

**Issue by qbait** [Diolor/Swipecards#83]
What's the fastest way to create card animation for undo feature.
Do I need modify library's code for that?

**Comment by kh0r** [comment]
To create a nice looking undo animation you have to store the last coordinates of the removed card. Have a look at the function named resetCardViewOnStack here: https://github.com/Diolor/Swipecards/blob/master/library/src/main/java/com/lorentzos/flingswipe/FlingCardListener.java#L189

**Comment by AungThiha** [comment]
Have you guys got it? I don't know how to add undo feature to the library. Please help!

**Comment by Diolor** [comment]
It's not yet supported. #168
