### ISSUE TITLE
This is not working with AsyncTask

### ISSUE THREAD

**Issue by rushank** [Diolor/Swipecards#86]
I have used this with the AsyncTask and the custom adapter but it is not working.

	class LoadAllProducts extends AsyncTask<String, String, String> {

		@Override
		protected void onPreExecute() {
			super.onPreExecute();

			pDialog = new ProgressDialog(MainActivity.this);
			pDialog.setMessage("Loading products. Please wait...");
			pDialog.setIndeterminate(false);
			pDialog.setCancelable(false);
			pDialog.show();

		}

		protected String doInBackground(String... args) {
			// Building Parameters
			List<NameValuePair> params = new ArrayList<NameValuePair>();

			params.add(new BasicNameValuePair("id", "1"));

			// getting JSON string from URL
			JSONObject json = jParser.makeHttpRequest(url_all_products, "GET",
					params);

			flingContainer.removeAllViewsInLayout();

			al.clear();
			al = new ArrayList<Product>();

			try {
				// Checking for SUCCESS TAG
				int success = json.getInt(TAG_SUCCESS);

				if (success == 1) {
					// products found
					// Getting Array of Products
					products = json.getJSONArray(TAG_PRODUCTS);
					al = new ArrayList<Product>();
					// looping through All Products
					Product pp;
					for (int i = 0; i < products.length(); i++) {

						JSONObject c = products.getJSONObject(i);

						// Storing each json item in variable

						name = c.getString(TAG_NAME);

						pp = new Product();

						pp.portal = c.getString(TAG_NAME);

						al.add(pp);
						pp = null;

					}

				} else {

				}

			} catch (JSONException e) {
				e.printStackTrace();
			}

			return null;
		}

		protected void onPostExecute(String file_url) {
			// dismiss the dialog after getting all products
			pDialog.dismiss();

			arrayAdapter = new ProductAdpater(MainActivity.this, R.layout.item,
					al);

			flingContainer.setAdapter(arrayAdapter);

		}
	}

and my custom adapter:

	private class ProductAdpater extends ArrayAdapter<Product> {

		Activity mContext;

		public ProductAdpater(Activity context, int resourceId,
				List<Product> items) {
			super(context, resourceId, items);

			try {
				this.mContext = context;
			
			} catch (Exception e) {
			
				e.printStackTrace();
			}

		}

		@Override
		public int getCount() {
			// TODO Auto-generated method stub
			return al.size();
		}

		@Override
		public long getItemId(int position) {
			// TODO Auto-generated method stub
			return position;
		}

		public View getView(final int position, View convertView,
				ViewGroup parent) {

			View view = convertView;
			ViewHolder holder = null;

			LayoutInflater mInflater = (LayoutInflater) mContext
					.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
			if (view == null) {
				view = mInflater.inflate(R.layout.item, parent, false);
				holder = new ViewHolder();
				holder.imgIcon = (ImageView) view
						.findViewById(R.id.img_product);
				holder.imageLeft = (ImageButton) view
						.findViewById(R.id.img_delete);
				holder.imageRight = (ImageButton) view
						.findViewById(R.id.img_wish);

				holder.tvBrand = (TextView) view.findViewById(R.id.tv_brand);
				holder.tvPortal = (TextView) view.findViewById(R.id.tv_portal);

				view.setTag(holder);
			} else
				holder = (ViewHolder) view.getTag();

			holder.imgIcon.setImageDrawable(getResources().getDrawable(
					R.drawable.amazon));

			// your image url
			String url = "http://javatechig.com/wp-content/uploads/2014/05/UniversalImageLoader-620x405.png";

			ImageLoader imageLoader = ImageLoader.getInstance();

			// ImageView imageView = (ImageView) findViewById(R.id.img_product);

			imageLoader.displayImage(url, holder.imgIcon);

			holder.imageLeft.setOnClickListener(new OnClickListener() {

				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					flingContainer.getTopCardListener().selectLeft();
				}
			});
			holder.imageRight.setOnClickListener(new OnClickListener() {

				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					flingContainer.getTopCardListener().selectRight();
				}
			});

			holder.tvPortal.setText((al.get(position).portal));
			return view;
		}

		class ViewHolder {

			ImageView imgIcon;
			ImageButton imageLeft, imageRight;
			TextView tvPrice, tvPortal, tvBrand;

		}

	}

It is shows the ProgressDialog dialog but after completing doInBackgrond task it is not display anything. 
Even there is not error log .

How can i solved this?

**Comment by rushank** [comment]
@Diolor @dwang999 @qichuan @mg6maciej   please check this . Now able to bind the data.

**Comment by anantshah93** [comment]
You have to create new dummy array list(no need to add data just assign) onCreate() and setadapter with new dummy blank array to your flingContainer. Then you can set again to its OnPostExcecute();

If it helps you try it...and let me know if it works.

Solution code:
OnCreate(){
....
ArrayList<String> dataObjectsArray = new ArrayList<String>();

ProductAdpater  arrayAdapter = new ProductAdpater(MainActivity.this, R.layout.item,
                dataObjectsArray);

flingContainer.setFlingListener().........
....

}
then set in OnPostExcecute(){
arrayAdapter = new ProductAdpater(MainActivity.this, R.layout.item,
                dataObjectsArray);
}

**Comment by rushank** [comment]
No. still it is not display any thing. My updated code:

package com.proconamix.myshop;

import java.util.ArrayList;
import java.util.List;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import android.app.Activity;
import android.app.ProgressDialog;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.StrictMode;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.lorentzos.flingswipe.SwipeFlingAdapterView;
import com.nostra13.universalimageloader.core.ImageLoader;
import com.proconamix.utills.Product;

/**
 * Removed the flicker
 * 
 */
public class MainActivity extends Activity {
	View menu;
	View app;
	boolean menuOut = false;
	private ArrayList<Product> al = new ArrayList<Product>();;
	private ArrayAdapter<Product> arrayAdapter;
	private int i;
	SwipeFlingAdapterView flingContainer;
	boolean isALL = false;
	int min = 2000, max = 5000;
	ImageView img_product;
	String pid;
	String name;
	// Progress Dialog
	private ProgressDialog pDialog;
	// Creating JSON Parser object
	JSONParser jParser = new JSONParser();

	// url to get all products list
	private static String url_all_products = "http://www.sysoftni.com/ideal/android/get_all_products.php";

	// JSON Node names
	private static final String TAG_SUCCESS = "psuccess";
	private static final String TAG_PRODUCTS = "products";

	private static final String TAG_NAME = "name";

	// products JSONArray
	JSONArray products = null;
	ArrayList dataObjectsArray;

	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		// requestWindowFeature(Window.FEATURE_NO_TITLE);
		setContentView(R.layout.slide_animation_then_call_layout);

		isALL = false;

		flingContainer = (SwipeFlingAdapterView) findViewById(R.id.frame);

		img_product = (ImageView) findViewById(R.id.img_product);

		StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder()
				.permitAll().build();
		StrictMode.setThreadPolicy(policy);

		new LoadAllProducts().execute();
		// loaddata();

		dataObjectsArray = new ArrayList();
		arrayAdapter = new ProductAdpater(MainActivity.this, dataObjectsArray);

	}

	private void loaddata() {
		List<NameValuePair> params = new ArrayList<NameValuePair>();

		params.add(new BasicNameValuePair("id", "1"));

		// getting JSON string from URL
		JSONObject json = jParser.makeHttpRequest(url_all_products, "GET",
				params);

		try {
			// Checking for SUCCESS TAG
			int success = json.getInt(TAG_SUCCESS);

			if (success == 1) {
				// products found
				// Getting Array of Products
				products = json.getJSONArray(TAG_PRODUCTS);

				// looping through All Products
				for (int i = 0; i < products.length(); i++) {

					JSONObject c = products.getJSONObject(i);

					// Storing each json item in variable

					name = c.getString(TAG_NAME);

					Product pp;
					pp = new Product();

					pp.portal = c.getString(TAG_NAME);

					al.add(pp);
					arrayAdapter = new ProductAdpater(MainActivity.this, al);

					// set the listener and the adapter
					flingContainer.setAdapter(arrayAdapter);

				}
			} else {

			}

		} catch (JSONException e) {
			e.printStackTrace();
			Toast.makeText(getApplicationContext(), "nai thay",
					Toast.LENGTH_LONG).show();
		}

	}

	private class ProductAdpater extends ArrayAdapter<Product> {

		Activity mContext;

		public ProductAdpater(Activity context, List<Product> items) {
			super(context, R.layout.item, items);

			try {
				this.mContext = context;
				// this.list = items;
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}

		}

		@Override
		public int getCount() {
			// TODO Auto-generated method stub
			return al.size();
		}

		@Override
		public long getItemId(int position) {
			// TODO Auto-generated method stub
			return position;
		}

		public View getView(final int position, View convertView,
				ViewGroup parent) {

			View view = convertView;
			ViewHolder holder = null;

			LayoutInflater mInflater = (LayoutInflater) mContext
					.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
			if (view == null) {
				view = mInflater.inflate(R.layout.item, parent, false);
				holder = new ViewHolder();
				holder.imgIcon = (ImageView) view
						.findViewById(R.id.img_product);
				holder.imageLeft = (ImageButton) view
						.findViewById(R.id.img_delete);
				holder.imageRight = (ImageButton) view
						.findViewById(R.id.img_wish);

				holder.tvBrand = (TextView) view.findViewById(R.id.tv_brand);
				holder.tvPortal = (TextView) view.findViewById(R.id.tv_portal);

				view.setTag(holder);
			} else
				holder = (ViewHolder) view.getTag();

			holder.imgIcon.setImageDrawable(getResources().getDrawable(
					R.drawable.amazon));

			// your image url
			String url = "http://javatechig.com/wp-content/uploads/2014/05/UniversalImageLoader-620x405.png";

			ImageLoader imageLoader = ImageLoader.getInstance();

			// ImageView imageView = (ImageView) findViewById(R.id.img_product);

			imageLoader.displayImage(url, holder.imgIcon);

			holder.imageLeft.setOnClickListener(new OnClickListener() {

				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					flingContainer.getTopCardListener().selectLeft();
				}
			});
			holder.imageRight.setOnClickListener(new OnClickListener() {

				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					flingContainer.getTopCardListener().selectRight();
				}
			});

			holder.tvPortal.setText((al.get(position).portal));
			return view;
		}

		class ViewHolder {

			ImageView imgIcon;
			ImageButton imageLeft, imageRight;
			TextView tvPrice, tvPortal, tvBrand;

		}

	}

	class LoadAllProducts extends AsyncTask<String, String, String> {

		@Override
		protected void onPreExecute() {
			super.onPreExecute();

			pDialog = new ProgressDialog(MainActivity.this);
			pDialog.setMessage("Loading products. Please wait...");
			pDialog.setIndeterminate(false);
			pDialog.setCancelable(false);
			pDialog.show();

		}

		protected String doInBackground(String... args) {
			// Building Parameters
			List<NameValuePair> params = new ArrayList<NameValuePair>();

			params.add(new BasicNameValuePair("id", "1"));

			// getting JSON string from URL
			JSONObject json = jParser.makeHttpRequest(url_all_products, "GET",
					params);

			al.clear();
			al = new ArrayList<Product>();

			try {
				// Checking for SUCCESS TAG
				int success = json.getInt(TAG_SUCCESS);

				if (success == 1) {
					// products found
					// Getting Array of Products
					products = json.getJSONArray(TAG_PRODUCTS);
					al = new ArrayList<Product>();
					// looping through All Products
					Product pp;
					for (int i = 0; i < products.length(); i++) {

						JSONObject c = products.getJSONObject(i);

						// Storing each json item in variable

						name = c.getString(TAG_NAME);

						pp = new Product();

						pp.portal = c.getString(TAG_NAME);

						al.add(pp);
						pp = null;

					}

				} else {

				}

			} catch (JSONException e) {
				e.printStackTrace();
				Toast.makeText(getApplicationContext(), "nai thay",
						Toast.LENGTH_LONG).show();
			}

			return null;
		}

		protected void onPostExecute(String file_url) {
			// dismiss the dialog after getting all products
			pDialog.dismiss();

			arrayAdapter = new ProductAdpater(MainActivity.this, al);

			arrayAdapter = new ProductAdpater(MainActivity.this,
					dataObjectsArray);
			
			flingContainer.setAdapter(arrayAdapter);

		}
	}
}

**Comment by rushank** [comment]
@anantshah93  is there any mistake in my updated code?

**Comment by rushank** [comment]
i have solved it . 

i have just put the  "arrayAdapter.notifyDataSetChanged();"  after 	flingContainer.setAdapter(mHomeviewAdapter);  in  onPostExecute method :

My new updated code on onPostExecute :

 protected void onPostExecute(String file_url) {
            pDialog.dismiss();

            arrayAdapter = new ProductAdpater(context, al);
            flingContainer.setAdapter(arrayAdapter);
            arrayAdapter.notifyDataSetChanged();
        }

**Comment by anantshah93** [comment]
@rushank good to see you found solution.
