### ISSUE TITLE
How to make user image into a card?!

### ISSUE THREAD

**Issue by qteen1** [Diolor/Swipecards#93]
Hey guys, so I want the users to be able to make their own cards. I have an image path from the user that I retrieved, but I can't seem to figure out how to turn that into a card they can swipe. This swipe code is structured in a particular way that I can't change the contentView, change the ImageView then reset the content view and have the image swiped?!?! Does anyone know how to do this and can provide an example!?!?

**Comment by herbig** [comment]
You'll need to read up on Android basics, in particular "creating custom list adapters."

Here's a decent resource I found on Google:

http://www.vogella.com/tutorials/AndroidListView/article.html
