### ISSUE TITLE
Swipe back in animation

### ISSUE THREAD

**Issue by AungThiha** [Diolor/Swipecards#99]
How do I undo swipe? I mean put back the card in with animation for some reason.

**Comment by AungThiha** [comment]
got it

**Comment by vanshg** [comment]
Hi, can you please explain how you managed to do this?

**Comment by monpac** [comment]
yes please!

**Comment by AungThiha** [comment]
How I've implemented in my app is really complicated. Even I don't remember how what I've written back then. :D I'll make it simple and make pull request soon. :)

**Comment by monpac** [comment]
lol, thanks!

**Comment by NehaDhanwani** [comment]
Anyone has done this already? @AungThiha Can u please share the github link?

**Comment by Rawall1** [comment]
@AungThiha can u please share how u did it?
